#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 43405cf1-a9cb-4745-adff-b2a7c40d2e2f
# Source File: C:\Users\plkarmic\PRV\Sync\GoLang\EnergyXLSX\GUI.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.152
     Generated on:       2018-10-11 08:50
     Generated by:       plkarmicadmin
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-GUI_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Define SAPIEN Types
	#----------------------------------------------
	try{
		[FolderBrowserModernDialog] | Out-Null
	}
	catch
	{
		Add-Type -ReferencedAssemblies ('System.Windows.Forms') -TypeDefinition  @" 
		using System;
		using System.Windows.Forms;
		using System.Reflection;

        namespace SAPIENTypes
        {
		    public class FolderBrowserModernDialog : System.Windows.Forms.CommonDialog
            {
                private System.Windows.Forms.OpenFileDialog fileDialog;
                public FolderBrowserModernDialog()
                {
                    fileDialog = new System.Windows.Forms.OpenFileDialog();
                    fileDialog.Filter = "Folders|\n";
                    fileDialog.AddExtension = false;
                    fileDialog.CheckFileExists = false;
                    fileDialog.DereferenceLinks = true;
                    fileDialog.Multiselect = false;
                    fileDialog.Title = "Select a folder";
                }

                public string Title
                {
                    get { return fileDialog.Title; }
                    set { fileDialog.Title = value; }
                }

                public string InitialDirectory
                {
                    get { return fileDialog.InitialDirectory; }
                    set { fileDialog.InitialDirectory = value; }
                }
                
                public string SelectedPath
                {
                    get { return fileDialog.FileName; }
                    set { fileDialog.FileName = value; }
                }

                object InvokeMethod(Type type, object obj, string method, object[] parameters)
                {
                    MethodInfo methInfo = type.GetMethod(method, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                    return methInfo.Invoke(obj, parameters);
                }

                bool ShowOriginalBrowserDialog(IntPtr hwndOwner)
                {
                    using(FolderBrowserDialog folderBrowserDialog = new FolderBrowserDialog())
                    {
                        folderBrowserDialog.Description = this.Title;
                        folderBrowserDialog.SelectedPath = !string.IsNullOrEmpty(this.SelectedPath) ? this.SelectedPath : this.InitialDirectory;
                        folderBrowserDialog.ShowNewFolderButton = false;
                        if (folderBrowserDialog.ShowDialog() == DialogResult.OK)
                        {
                            fileDialog.FileName = folderBrowserDialog.SelectedPath;
                            return true;
                        }
                        return false;
                    }
                }

                protected override bool RunDialog(IntPtr hwndOwner)
                {
                    if (Environment.OSVersion.Version.Major >= 6)
                    {      
                        try
                        {
                            bool flag = false;
                            System.Reflection.Assembly assembly = Assembly.Load("System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
                            Type typeIFileDialog = assembly.GetType("System.Windows.Forms.FileDialogNative").GetNestedType("IFileDialog", BindingFlags.NonPublic);
                            uint num = 0;
                            object dialog = InvokeMethod(fileDialog.GetType(), fileDialog, "CreateVistaDialog", null);
                            InvokeMethod(fileDialog.GetType(), fileDialog, "OnBeforeVistaDialog", new object[] { dialog });
                            uint options = (uint)InvokeMethod(typeof(System.Windows.Forms.FileDialog), fileDialog, "GetOptions", null) | (uint)0x20;
                            InvokeMethod(typeIFileDialog, dialog, "SetOptions", new object[] { options });
                            Type vistaDialogEventsType = assembly.GetType("System.Windows.Forms.FileDialog").GetNestedType("VistaDialogEvents", BindingFlags.NonPublic);
                            object pfde = Activator.CreateInstance(vistaDialogEventsType, fileDialog);
                            object[] parameters = new object[] { pfde, num };
                            InvokeMethod(typeIFileDialog, dialog, "Advise", parameters);
                            num = (uint)parameters[1];
                            try
                            {
                                int num2 = (int)InvokeMethod(typeIFileDialog, dialog, "Show", new object[] { hwndOwner });
                                flag = 0 == num2;
                            }
                            finally
                            {
                                InvokeMethod(typeIFileDialog, dialog, "Unadvise", new object[] { num });
                                GC.KeepAlive(pfde);
                            }
                            return flag;
                        }
                        catch
                        {
                            return ShowOriginalBrowserDialog(hwndOwner);
                        }
                    }
                    else
                        return ShowOriginalBrowserDialog(hwndOwner);
                }

                public override void Reset()
                {
                    fileDialog.Reset();
                }
            }
       }
"@ -IgnoreWarnings | Out-Null
	}
	#endregion Define SAPIEN Types

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formEnergiaRaport = New-Object 'System.Windows.Forms.Form'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$buttonGenerujRaport = New-Object 'System.Windows.Forms.Button'
	$labelProszęKatalogDocelow = New-Object 'System.Windows.Forms.Label'
	$labelKatalogDocelowy = New-Object 'System.Windows.Forms.Label'
	$buttonWybierzKatalogDocelo = New-Object 'System.Windows.Forms.Button'
	$labelProszęWybraćPlikŹród = New-Object 'System.Windows.Forms.Label'
	$buttonWybierzPlikRaportu = New-Object 'System.Windows.Forms.Button'
	$labelPlikRaportuSAP = New-Object 'System.Windows.Forms.Label'
	$openfiledialog1 = New-Object 'System.Windows.Forms.OpenFileDialog'
	$folderbrowsermoderndialog1 = New-Object 'SAPIENTypes.FolderBrowserModernDialog'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formEnergiaRaport_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$labelPlikRaportuSAP_Click={
		#TODO: Place custom script here
		
	}
	
	$openfiledialog1_FileOk=[System.ComponentModel.CancelEventHandler]{
	#Event Argument: $_ = [System.ComponentModel.CancelEventArgs]
		#TODO: Place custom script here
		
	}
	
	$buttonWybierzPlikRaportu_Click={
		#TODO: Place custom script here
		$openfiledialog1.ShowDialog()
		$global:fileName = $openfiledialog1.FileName
		$labelProszęWybraćPlikŹród.Text = $global:fileName
		$textbox1.Text += "Plik raportu SAP: $global:fileName `r`n"
	}
	
	$labelKatalogDocelowy_Click={
		#TODO: Place custom script here
		
	}
	
	$labelProszęWybraćPlikŹród_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonWybierzKatalogDocelo_Click={
		#TODO: Place custom script here
		$folderbrowsermoderndialog1.ShowDialog()
		$global:folderDocelowy = $folderbrowsermoderndialog1.SelectedPath
		$labelProszęKatalogDocelow.Text = $global:folderDocelowy
		$textbox1.Text += "Folder docelowy: $global:folderDocelowy `r`n"
	}
	
	$labelProszęKatalogDocelow_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonGenerujRaport_Click={
		#TODO: Place custom script here
		Write-Host $global:fileName
		Write-Host $global:folderDocelowy
		Write-Host "Uruchamiam process: raportEnergia.exe " $global:fileName $global:folderDocelowy
		#Start-Process raportEnergia.exe -ArgumentList "$global:fileName $global:folderDocelowy" -Wait
		$cmdOutput = & .\raportEnergia.exe $global:fileName $global:folderDocelowy
		$textbox1.Text += "GOTOWE `r`n"
		start $global:folderDocelowy
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formEnergiaRaport.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonGenerujRaport.remove_Click($buttonGenerujRaport_Click)
			$labelProszęKatalogDocelow.remove_Click($labelProszęKatalogDocelow_Click)
			$labelKatalogDocelowy.remove_Click($labelKatalogDocelowy_Click)
			$buttonWybierzKatalogDocelo.remove_Click($buttonWybierzKatalogDocelo_Click)
			$labelProszęWybraćPlikŹród.remove_Click($labelProszęWybraćPlikŹród_Click)
			$buttonWybierzPlikRaportu.remove_Click($buttonWybierzPlikRaportu_Click)
			$labelPlikRaportuSAP.remove_Click($labelPlikRaportuSAP_Click)
			$formEnergiaRaport.remove_Load($formEnergiaRaport_Load)
			$openfiledialog1.remove_FileOk($openfiledialog1_FileOk)
			$formEnergiaRaport.remove_Load($Form_StateCorrection_Load)
			$formEnergiaRaport.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formEnergiaRaport.SuspendLayout()
	#
	# formEnergiaRaport
	#
	$formEnergiaRaport.Controls.Add($textbox1)
	$formEnergiaRaport.Controls.Add($buttonGenerujRaport)
	$formEnergiaRaport.Controls.Add($labelProszęKatalogDocelow)
	$formEnergiaRaport.Controls.Add($labelKatalogDocelowy)
	$formEnergiaRaport.Controls.Add($buttonWybierzKatalogDocelo)
	$formEnergiaRaport.Controls.Add($labelProszęWybraćPlikŹród)
	$formEnergiaRaport.Controls.Add($buttonWybierzPlikRaportu)
	$formEnergiaRaport.Controls.Add($labelPlikRaportuSAP)
	$formEnergiaRaport.AutoScaleDimensions = '10, 25'
	$formEnergiaRaport.AutoScaleMode = 'Font'
	$formEnergiaRaport.BackColor = 'Control'
	$formEnergiaRaport.ClientSize = '757, 401'
	$formEnergiaRaport.Font = 'Segoe UI, 9pt'
	#region Binary Data
	$formEnergiaRaport.Icon = [System.Convert]::FromBase64String('
AAABAAcAQEAAAAEAIAAoQgAAdgAAADAwAAABACAAqCUAAJ5CAAAoKAAAAQAgAGgaAABGaAAAICAA
AAEAIACoEAAAroIAABgYAAABACAAiAkAAFaTAAAUFAAAAQAgALgGAADenAAAEBAAAAEAIABoBAAA
lqMAACgAAABAAAAAgAAAAAEAIAAAAAAAAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/eHh4/3h4eP94
eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4
eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4
/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP95eXk+
AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4
eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4
/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/
eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh49AAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv//////////////
////////////////////////////////////////////////////////mZmZ/5mZmf//////////
////////////////////////////////////////////////////////////mZmZ/5mZmf//////
///////////////////////////////////////////////////////////9/f3/eHh4/3h4eP8A
AAAAAAAAAAAAAAAAAAAAZoI+/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/hqtS/2aCPv9mgj7/////////////////////////////////////////////////////
/////////////////5mZmf+ZmZn/////////////////////////////////////////////////
/////////////////////5mZmf+ZmZn/////////////////////////////////////////////
/////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+////////////////
//////////////////////////////////////////////////////+ZmZn/mZmZ////////////
//////////////////////////////////////////////////////////+ZmZn/mZmZ////////
//////////////////////////////////////////////////////////39/f94eHj/eHh4/wAA
AAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra2v/a2tr/hqtS
/4arUv+Gq1L/ZoI+/2aCPv//////////////////////////////////////////////////////
////////////////mZmZ/5mZmf//////////////////////////////////////////////////
////////////////////mZmZ/5mZmf//////////////////////////////////////////////
///////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv+Gq1L/hqtS
/4arUv/a2tr/2tra/9ra2v/a2tr/2tra/4arUv+Gq1L/hqtS/2aCPv9mgj7/////////////////
/////////////////////////////////////////////////////5mZmf+ZmZn/////////////
/////////////////////////////////////////////////////////5mZmf+ZmZn/////////
/////////////////////////////////////////////////////////f39/3h4eP94eHj/AAAA
AAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/
hqtS/4arUv9mgj7/ZoI+////////////////////////////////////////////////////////
//////////////+ZmZn/mZmZ////////////////////////////////////////////////////
//////////////////+ZmZn/mZmZ////////////////////////////////////////////////
//////////////////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv//////////////////
////////////////////////////////////////////////////mZmZ/5mZmf//////////////
////////////////////////////////////////////////////////mZmZ/5mZmf//////////
///////////////////////////////////////////////////////9/f3/eHh4/3h4eP8AAAAA
AAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZ
mf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/5mZmf+ZmZn/mZmZ/5mZ
mf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf94eHj/eHh4/wAAAAAA
AAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/ZoI+/2aCPv//////////////////////////////////////////////////////////
////////////mZmZ/5mZmf//////////////////////////////////////////////////////
////////////////mZmZ/5mZmf//////////////////////////////////////////////////
///////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv+Gq1L/hqtS/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/////////////////////
/////////////////////////////////////////////////5mZmf+ZmZn/////////////////
/////////////////////////////////////////////////////5mZmf+ZmZn/////////////
/////////////////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAA
AAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/4arUv9mgj7/ZoI+////////////////////////////////////////////////////////////
//////////+ZmZn/mZmZ////////////////////////////////////////////////////////
//////////////+ZmZn/mZmZ////////////////////////////////////////////////////
//////////////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS
/9ra2v/a2tr/2tra/9ra2v/a2tr/hqtS/4arUv+Gq1L/ZoI+/2aCPv//////////////////////
////////////////////////////////////////////////mZmZ/5mZmf//////////////////
////////////////////////////////////////////////////mZmZ/5mZmf//////////////
///////////////////////////////////////////////////9/f3/eHh4/3h4eP8AAAAAAAAA
AAAAAAAAAAAAZoI+/2aCPv+Gq1L/hqtS/4arUv/a2tr/2tra/9ra2v/a2tr/2tra/4arUv+Gq1L/
hqtS/2aCPv9mgj7/////////////////////////////////////////////////////////////
/////////5mZmf+ZmZn/////////////////////////////////////////////////////////
/////////////5mZmf+ZmZn/////////////////////////////////////////////////////
/////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+////////////////////////
//////////////////////////////////////////////+ZmZn/mZmZ////////////////////
//////////////////////////////////////////////////+ZmZn/mZmZ////////////////
//////////////////////////////////////////////////39/f94eHj/eHh4/wAAAAAAAAAA
AAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+G
q1L/ZoI+/2aCPv//////////////////////////////////////////////////////////////
////////mZmZ/5mZmf//////////////////////////////////////////////////////////
////////////mZmZ/5mZmf//////////////////////////////////////////////////////
///////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/mZmZ/5mZmf+ZmZn/mZmZ/5mZ
mf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/3h4eP94eHj/AAAAAAAAAAAA
AAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+Z
mZn/mZmZ/5mZmf94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv//////////////////////////
////////////////////////////////////////////mZmZ/5mZmf//////////////////////
////////////////////////////////////////////////mZmZ/5mZmf//////////////////
///////////////////////////////////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAA
AAAAAAAAZoI+/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/2aCPv9mgj7/////////////////////////////////////////////////////////////////
/////5mZmf+ZmZn/////////////////////////////////////////////////////////////
/////////5mZmf+ZmZn/////////////////////////////////////////////////////////
/////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+////////////////////////////
//////////////////////////////////////////+ZmZn/mZmZ////////////////////////
//////////////////////////////////////////////+ZmZn/mZmZ////////////////////
//////////////////////////////////////////////39/f94eHj/eHh4/wAAAAAAAAAAAAAA
AAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra2v/a2tr/hqtS/4arUv+Gq1L/
ZoI+/2aCPv//////////////////////////////////////////////////////////////////
////mZmZ/5mZmf//////////////////////////////////////////////////////////////
////////mZmZ/5mZmf//////////////////////////////////////////////////////////
///////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv+Gq1L/hqtS/4arUv/a2tr/
2tra/9ra2v/a2tr/2tra/4arUv+Gq1L/hqtS/2aCPv9mgj7/////////////////////////////
/////////////////////////////////////////5mZmf+ZmZn/////////////////////////
/////////////////////////////////////////////5mZmf+ZmZn/////////////////////
/////////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAA
AAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9m
gj7/ZoI+////////////////////////////////////////////////////////////////////
//+ZmZn/mZmZ////////////////////////////////////////////////////////////////
//////+ZmZn/mZmZ////////////////////////////////////////////////////////////
//////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv//////////////////////////////
////////////////////////////////////////mZmZ/5mZmf//////////////////////////
////////////////////////////////////////////mZmZ/5mZmf//////////////////////
///////////////////////////////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAA
AAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+Z
mZn/mZmZ/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+Z
mZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf94eHj/eHh4/wAAAAAAAAAAAAAAAAAA
AABmgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+
/2aCPv//////////////////////////////////////////////////////////////////////
mZmZ/5mZmf//////////////////////////////////////////////////////////////////
////mZmZ/5mZmf//////////////////////////////////////////////////////////////
///9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/////////////////////////////////
/////////////////////////////////////5mZmf+ZmZn/////////////////////////////
/////////////////////////////////////////5mZmf+ZmZn/////////////////////////
/////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAA
AGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/
ZoI+//////////////////////////////////////////////////////////////////////+Z
mZn/mZmZ////////////////////////////////////////////////////////////////////
//+ZmZn/mZmZ////////////////////////////////////////////////////////////////
//39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/9ra2v/a2tr/
2tra/9ra2v/a2tr/hqtS/4arUv+Gq1L/ZoI+/2aCPv//////////////////////////////////
////////////////////////////////////mZmZ/5mZmf//////////////////////////////
////////////////////////////////////////mZmZ/5mZmf//////////////////////////
///////////////////////////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAA
ZoI+/2aCPv+Gq1L/hqtS/4arUv/a2tr/2tra/9ra2v/a2tr/2tra/4arUv+Gq1L/hqtS/2aCPv9m
gj7//////////////////////////////////////////////////////////////////////5mZ
mf+ZmZn/////////////////////////////////////////////////////////////////////
/5mZmf+ZmZn/////////////////////////////////////////////////////////////////
/f39/3h4eP94eHj7AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+////////////////////////////////////
//////////////////////////////////+ZmZn/mZmZ////////////////////////////////
//////////////////////////////////////+ZmZn/mZmZ////////////////////////////
//////////////////////////////////////39/f94eHj/eHh4+wAAAAAAAAAAAAAAAAAAAABm
gj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aC
Pv//////////////////////////////////////////////////////////////////////mZmZ
/5mZmf//////////////////////////////////////////////////////////////////////
mZmZ/5mZmf/////////////////////////////////////////////////////////////////9
/f3/eHh4/3h4ePsAAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+Z
mZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/3h4eP94eHj7AAAAAAAAAAAAAAAAAAAAAGaC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+Z
mZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZ
mf94eHj/eHh4+wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv//////////////////////////////////////
////////////////////////////////mZmZ/5mZmf//////////////////////////////////
////////////////////////////////////mZmZ/5mZmf//////////////////////////////
///////////////////////////////////9/f3/eHh4/3h4ePsAAAAAAAAAAAAAAAAAAAAAZoI+
/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/
/////////////////////////////////////////////////////////////////////5mZmf+Z
mZn//////////////////////////////////////////////////////////////////////5mZ
mf+ZmZn//////////////////////////////////////////////////////////////////f39
/3h4eP94eHj7AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+////////////////////////////////////////
//////////////////////////////+ZmZn/mZmZ////////////////////////////////////
//////////////////////////////////+ZmZn/mZmZ////////////////////////////////
//////////////////////////////////39/f94eHj/eHh4+wAAAAAAAAAAAAAAAAAAAABmgj7/
ZoI+/4arUv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra2v/a2tr/hqtS/4arUv+Gq1L/ZoI+/2aCPv//
////////////////////////////////////////////////////////////////////mZmZ/5mZ
mf//////////////////////////////////////////////////////////////////////mZmZ
/5mZmf/////////////////////////////////////////////////////////////////9/f3/
eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv+Gq1L/hqtS/4arUv/a2tr/2tra/9ra2v/a
2tr/2tra/4arUv+Gq1L/hqtS/2aCPv9mgj7/////////////////////////////////////////
/////////////////////////////5mZmf+ZmZn/////////////////////////////////////
/////////////////////////////////5mZmf+ZmZn/////////////////////////////////
/////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9m
gj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+////
//////////////////////////////////////////////////////////////////+ZmZn/mZmZ
//////////////////////////////////////////////////////////////////////+ZmZn/
mZmZ//////////////////////////////////////////////////////////////////39/f94
eHj/eHh4/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv//////////////////////////////////////////
////////////////////////////mZmZ/5mZmf//////////////////////////////////////
////////////////////////////////mZmZ/5mZmf//////////////////////////////////
///////////////////////////////9/f3/eHh4/3l5ef8AAAAAAAAAAAAAAAAAAAAAZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2yJQf9nhD//ZoI+/2aCPv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aC
Pv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+
/2aCPv8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/
dpZH/2aCPv9phkD/fJ5M/2aCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/
hqtS/4arUv+Gq1L/hqtS/4arUv98nkz/aYZA/2aCPv92lkf/hqtS/4arUv9mgj7/ZoI+/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/
ZoI+/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv9siUH/ZoI+/2yJQf+G
q1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv+Gq1L/hqtS/4arUv+Gq1L/2tra/9ra2v/a2tr/2tra/9ra
2v+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv+Gq1L/hqtS/4arUv+Gq1L/2tra/9ra2v/a2tr/2tra
/9ra2v+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv+Gq1L/hqtS/4arUv+Gq1L/2tra/9ra2v/a2tr/
2tra/9ra2v+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv+G
q1L/hqtS/3aWR/9mgj7/aYZA/3yeTP+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/hqtS/4ar
Uv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra2v/a2tr/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/hqtS
/4arUv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra2v/a2tr/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/
hqtS/4arUv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra2v/a2tr/hqtS/4arUv+Gq1L/hqtS/2aCPv9m
gj7/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/fJ5M/2mGQP9mgj7/dpZH/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/hqtS/4arUv9mgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/ZoI+/wAAAAAAAAAAAAAAAAAAAABmgj7/ZoI+/2eE
P/9siUH/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aCPv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/2aC
Pv8AAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/AAAAAAAAAAAAAAAAAAAAAGaCPplmgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA////////////////////////////////////////////////////////////
////gAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAA
AAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAA
B4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAH
gAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeA
AAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AA
AAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAA
AAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAA
AAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAeAAAAAAAAAB///////
//////////////8oAAAAMAAAAGAAAAABACAAAAAAAIAlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaCPplmgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4
/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/
eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHjSAAAAAAAAAAAAAAAAAAAAAGaCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv94eHj/eHh4/3h4eP94eHj/eHh4/3h4
eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4
/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/
AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//
////////////////////////////////////////////////////mZmZ////////////////////
//////////////////////////////////+ZmZn/////////////////////////////////////
/////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////////////////////
////mZmZ//////////////////////////////////////////////////////+ZmZn/////////
/////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAA
AGaCPv9mgj7/hqtS/4arUv/a2tr/2tra/9ra2v+Gq1L/hqtS/2aCPv//////////////////////
////////////////////////////////mZmZ////////////////////////////////////////
//////////////+ZmZn//////////////////////////////////////////////////f39/3h4
eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/2aCPv//////////////////////////////////////////////////////mZmZ////////////
//////////////////////////////////////////+ZmZn/////////////////////////////
/////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////////////
////////////mZmZ//////////////////////////////////////////////////////+ZmZn/
/////////////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAA
AAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv+ZmZn/mZmZ/5mZ
mf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
r6+v/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+G
q1L/hqtS/2aCPv//////////////////////////////////////////////////////mZmZ////
//////////////////////////////////////////////////+ZmZn/////////////////////
/////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/
hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////
////////////////////mZmZ////////////////////////////////////////////////////
//+ZmZn//////////////////////////////////////////////////f39/3h4eP94eHj/AAAA
AAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv/a2tr/2tra/9ra2v+Gq1L/hqtS/2aCPv//////
////////////////////////////////////////////////mZmZ////////////////////////
//////////////////////////////+ZmZn/////////////////////////////////////////
/////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////////////////////////
mZmZ//////////////////////////////////////////////////////+ZmZn/////////////
/////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaC
Pv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////
////////////////////////////mZmZ////////////////////////////////////////////
//////////+ZmZn//////////////////////////////////////////////////f39/3h4eP94
eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/r6+v/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////////////////
////////mZmZ//////////////////////////////////////////////////////+ZmZn/////
/////////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAA
AAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////
////////////////////////////////////mZmZ////////////////////////////////////
//////////////////+ZmZn//////////////////////////////////////////////////f39
/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv/a2tr/2tra/9ra2v+Gq1L/
hqtS/2aCPv//////////////////////////////////////////////////////mZmZ////////
//////////////////////////////////////////////+ZmZn/////////////////////////
/////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////////
////////////////mZmZ//////////////////////////////////////////////////////+Z
mZn//////////////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAA
AAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////
////////////////////////////////////////////mZmZ////////////////////////////
//////////////////////////+ZmZn/////////////////////////////////////////////
/////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/r6+v/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9m
gj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////
////////////////////////mZmZ////////////////////////////////////////////////
//////+ZmZn//////////////////////////////////////////////////f39/3h4eP94eHj/
AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//
////////////////////////////////////////////////////mZmZ////////////////////
//////////////////////////////////+ZmZn/////////////////////////////////////
/////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv/a2tr/
2tra/9ra2v+Gq1L/hqtS/2aCPv//////////////////////////////////////////////////
////mZmZ//////////////////////////////////////////////////////+ZmZn/////////
/////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAA
AGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////
////////////////////////////////mZmZ////////////////////////////////////////
//////////////+ZmZn//////////////////////////////////////////////////f39/3h4
eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/2aCPv//////////////////////////////////////////////////////mZmZ////////////
//////////////////////////////////////////+ZmZn/////////////////////////////
/////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/r6+v/3h4eP94eHj/AAAAAAAAAAAA
AAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////
////////////////////////////////////////mZmZ////////////////////////////////
//////////////////////+ZmZn/////////////////////////////////////////////////
/f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+G
q1L/hqtS/2aCPv//////////////////////////////////////////////////////mZmZ////
//////////////////////////////////////////////////+ZmZn/////////////////////
/////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/
hqtS/4arUv/a2tr/2tra/9ra2v+Gq1L/hqtS/2aCPv//////////////////////////////////
////////////////////mZmZ////////////////////////////////////////////////////
//+ZmZn//////////////////////////////////////////////////f39/3h4eP94eHj/AAAA
AAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////
////////////////////////////////////////////////mZmZ////////////////////////
//////////////////////////////+ZmZn/////////////////////////////////////////
/////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////////////////////////
mZmZ//////////////////////////////////////////////////////+ZmZn/////////////
/////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAGaC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv90lEf/aodA/2aC
Pv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/hqtS/4arUv+G
q1L/f6JO/2qHQP9qh0D/f6JO/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/AAAAAAAAAAAAAAAA
AAAAAGaCPv9mgj7/hqtS/4arUv90lEf/aIQ//3SUR/+Gq1L/hqtS/2aCPv+Gq1L/hqtS/4arUv/a
2tr/2tra/9ra2v/a2tr/hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra
2v+Gq1L/hqtS/4arUv9mgj7/hqtS/4arUv+Gq1L/2tra/9ra2v/a2tr/2tra/4arUv+Gq1L/hqtS
/2aCPv9mgj7/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/f6JO/2qHQP9qh0D/f6JO/4arUv+Gq1L/
hqtS/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/hqtS/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/AAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/aodA
/3SUR/+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/
hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9m
gj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv9mgj7/AAAAAAAA
AAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/AAAAAAAAAAAAAAAAAAAAAGaCPplmgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj6ZAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////AAD///////8AAP///////wAA
////////AAD///////8AAP///////wAA////////AACAAAAAAAcAAIAAAAAABwAAgAAAAAAHAACA
AAAAAAcAAIAAAAAABwAAgAAAAAAHAACAAAAAAAcAAIAAAAAABwAAgAAAAAAHAACAAAAAAAcAAIAA
AAAABwAAgAAAAAAHAACAAAAAAAcAAIAAAAAABwAAgAAAAAAHAACAAAAAAAcAAIAAAAAABwAAgAAA
AAAHAACAAAAAAAcAAIAAAAAABwAAgAAAAAAHAACAAAAAAAcAAIAAAAAABwAAgAAAAAAHAACAAAAA
AAcAAIAAAAAABwAAgAAAAAAHAACAAAAAAAcAAIAAAAAABwAAgAAAAAAHAACAAAAAAAcAAIAAAAAA
BwAAgAAAAAAHAACAAAAAAAcAAIAAAAAABwAAgAAAAAAHAACAAAAAAAcAAIAAAAAABwAAgAAAAAAH
AAD///////8AAP///////wAAKAAAACgAAABQAAAAAQAgAAAAAABAGgAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2ZmZv9mZmb/ZmZm/2Zm
Zv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm
/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/AAAAAAAAAAAAAAAAAAAAAGaCPv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////
/////////7CwsP///////////////////////////////////////////7CwsP//////////////
///////////////////+/v7/ZmZm/wAAAAAAAAAAAAAAAAAAAABmgj7/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv9mgj7///////////////////////////////////////////+ZmZn/
//////////////////////////////////////////+ZmZn/////////////////////////////
/////v7+/2ZmZv8AAAAAAAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/2tra/9ra2v/a2tr/2tra/4ar
Uv+Gq1L/ZoI+////////////////////////////////////////////mZmZ////////////////
////////////////////////////mZmZ//////////////////////////////////7+/v9mZmb/
AAAAAAAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//
/////////////////////////////////////////5mZmf//////////////////////////////
/////////////5mZmf/////////////////////////////////+/v7/ZmZm/wAAAAAAAAAAAAAA
AAAAAABmgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+Z
mZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/sLCw/2ZmZv8AAAAAAAAAAAAAAAAAAAAAZoI+/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////////////////////////
////////////mZmZ////////////////////////////////////////////mZmZ////////////
//////////////////////7+/v9mZmb/AAAAAAAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/2aCPv///////////////////////////////////////////5mZ
mf///////////////////////////////////////////5mZmf//////////////////////////
///////+/v7/ZmZm/wAAAAAAAAAAAAAAAAAAAABmgj7/hqtS/4arUv/a2tr/2tra/9ra2v/a2tr/
hqtS/4arUv9mgj7///////////////////////////////////////////+ZmZn/////////////
//////////////////////////////+ZmZn//////////////////////////////////v7+/2Zm
Zv8AAAAAAAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+
////////////////////////////////////////////mZmZ////////////////////////////
////////////////mZmZ//////////////////////////////////7+/v9mZmb/AAAAAAAAAAAA
AAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv+ZmZn/mZmZ/5mZ
mf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+wsLD/ZmZm/wAAAAAAAAAAAAAAAAAAAABmgj7/
hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/////////////////////////////
//////////////+ZmZn///////////////////////////////////////////+ZmZn/////////
/////////////////////////v7+/2ZmZv8AAAAAAAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////////////////////////////////////
mZmZ////////////////////////////////////////////mZmZ////////////////////////
//////////7+/v9mZmb/AAAAAAAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra
2v+Gq1L/hqtS/2aCPv///////////////////////////////////////////5mZmf//////////
/////////////////////////////////5mZmf/////////////////////////////////+/v7/
ZmZm/wAAAAAAAAAAAAAAAAAAAABmgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9m
gj7///////////////////////////////////////////+ZmZn/////////////////////////
//////////////////+ZmZn//////////////////////////////////v7+/2ZmZv8AAAAAAAAA
AAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+Z
mZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/7CwsP9mZmb/AAAAAAAAAAAAAAAAAAAAAGaC
Pv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////
/////////////////5mZmf///////////////////////////////////////////5mZmf//////
///////////////////////////+/v7/ZmZm/wAAAAAAAAAAAAAAAAAAAABmgj7/hqtS/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/////////////////////////////////////////
//+ZmZn///////////////////////////////////////////+ZmZn/////////////////////
/////////////v7+/2ZmZv8AAAAAAAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/2tra/9ra2v/a2tr/
2tra/4arUv+Gq1L/ZoI+////////////////////////////////////////////mZmZ////////
////////////////////////////////////mZmZ//////////////////////////////////7+
/v9mZmb/AAAAAAAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/2aCPv///////////////////////////////////////////5mZmf//////////////////////
/////////////////////5mZmf/////////////////////////////////+/v7/ZmZm/wAAAAAA
AAAAAAAAAAAAAABmgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/mZmZ/5mZ
mf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/sLCw/2ZmZv8AAAAAAAAAAAAAAAAAAAAA
ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////////////////
////////////////////mZmZ////////////////////////////////////////////mZmZ////
//////////////////////////////7+/v9mZmb/AAAAAAAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////////////////////////////
/////5mZmf///////////////////////////////////////////5mZmf//////////////////
///////////////+/v7/ZmZm/wAAAAAAAAAAAAAAAAAAAABmgj7/hqtS/4arUv/a2tr/2tra/9ra
2v/a2tr/hqtS/4arUv9mgj7///////////////////////////////////////////+ZmZn/////
//////////////////////////////////////+ZmZn/////////////////////////////////
/v7+/2ZmZv8AAAAAAAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+G
q1L/ZoI+////////////////////////////////////////////sLCw////////////////////
////////////////////////sLCw//////////////////////////////////7+/v9mZmb/AAAA
AAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/wAAAAAAAAAAAAAAAAAA
AABmgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/bIlB/2eEP/9mgj7/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/
hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv8AAAAAAAAAAAAAAAAAAAAAZoI+/4arUv+G
q1L/hqtS/4arUv92lkf/ZoI+/2mGQP98nkz/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4ar
Uv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv9mgj7/AAAAAAAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS/3yeTP9mgj7/
ZoI+/3yeTP+Gq1L/hqtS/2aCPv+Gq1L/hqtS/9ra2v/a2tr/2tra/9ra2v+Gq1L/hqtS/2aCPv+G
q1L/hqtS/9ra2v/a2tr/2tra/9ra2v+Gq1L/hqtS/2aCPv+Gq1L/hqtS/9ra2v/a2tr/2tra/4ar
Uv+Gq1L/ZoI+/wAAAAAAAAAAAAAAAAAAAABmgj7/fJ5M/2mGQP9mgj7/dpZH/4arUv+Gq1L/hqtS
/4arUv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/hqtS/4arUv+Gq1L/
hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv8A
AAAAAAAAAAAAAAAAAAAAZoI+/2eEP/9siUH/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/AAAAAAAAAAAAAAAA
AAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAD//////wAAAP//////AAAA//////8AAAD//////wAAAP//////AAAA
AAAAAA8AAAAAAAAADwAAAAAAAAAPAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAPAAAAAAAAAA8AAAAA
AAAADwAAAAAAAAAPAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAPAAAAAAAAAA8AAAAAAAAADwAAAAAA
AAAPAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAPAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAPAAAAAAAA
AA8AAAAAAAAADwAAAAAAAAAPAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAPAAAAAAAAAA8AAAAAAAAA
DwAAAAAAAAAPAAAAAAAAAA8AAAAAAAAADwAAAP//////AAAA//////8AAAD//////wAAACgAAAAg
AAAAQAAAAAEAIAAAAAAAgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/
ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/ZmZm/2ZmZv9mZmb/AAAAAAAAAAAAAAAAZoI+/4arUv+G
q1L/hqtS/4arUv+Gq1L/hqtS/2aCPv////////////////////////////////+wsLD/////////
////////////////////////sLCw/////////////////////////////v7+/2ZmZv8AAAAAAAAA
AAAAAABmgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////////////////////
/////5mZmf////////////////////////////////+ZmZn////////////////////////////+
/v7/ZmZm/wAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS/9ra2v/a2tr/hqtS/4arUv9mgj7/////////
////////////////////////mZmZ/////////////////////////////////5mZmf//////////
//////////////////7+/v9mZmb/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/
hqtS/2aCPv////////////////////////////////+ZmZn/////////////////////////////
////mZmZ/////////////////////////////v7+/2ZmZv8AAAAAAAAAAAAAAABmgj7/ZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+wsLD/ZmZm/wAAAAAAAAAA
AAAAAGaCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/////////////////////////////
////mZmZ/////////////////////////////////5mZmf////////////////////////////7+
/v9mZmb/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////
//////////////////////+ZmZn/////////////////////////////////mZmZ////////////
/////////////////v7+/2ZmZv8AAAAAAAAAAAAAAABmgj7/hqtS/4arUv/a2tr/2tra/4arUv+G
q1L/ZoI+/////////////////////////////////5mZmf//////////////////////////////
//+ZmZn////////////////////////////+/v7/ZmZm/wAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/4arUv9mgj7/////////////////////////////////mZmZ////////////
/////////////////////5mZmf////////////////////////////7+/v9mZmb/AAAAAAAAAAAA
AAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZ
mf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/sLCw
/2ZmZv8AAAAAAAAAAAAAAABmgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////
/////////////////////5mZmf////////////////////////////////+ZmZn/////////////
///////////////+/v7/ZmZm/wAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4ar
Uv9mgj7/////////////////////////////////mZmZ////////////////////////////////
/5mZmf////////////////////////////7+/v9mZmb/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/
2tra/9ra2v+Gq1L/hqtS/2aCPv////////////////////////////////+ZmZn/////////////
////////////////////mZmZ/////////////////////////////v7+/2ZmZv8AAAAAAAAAAAAA
AABmgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////////////////////////
/5mZmf////////////////////////////////+ZmZn////////////////////////////+/v7/
ZmZm/wAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/mZmZ/5mZmf+Z
mZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZ
mf+ZmZn/mZmZ/7CwsP9mZmb/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/2aCPv////////////////////////////////+ZmZn/////////////////////////////////
mZmZ/////////////////////////////v7+/2ZmZv8AAAAAAAAAAAAAAABmgj7/hqtS/4arUv+G
q1L/hqtS/4arUv+Gq1L/ZoI+/////////////////////////////////5mZmf//////////////
//////////////////+ZmZn////////////////////////////+/v7/ZmZm/wAAAAAAAAAAAAAA
AGaCPv+Gq1L/hqtS/9ra2v/a2tr/hqtS/4arUv9mgj7/////////////////////////////////
mZmZ/////////////////////////////////5mZmf////////////////////////////7+/v9m
Zmb/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////////
//////////////////+wsLD/////////////////////////////////sLCw////////////////
/////////////v7+/2ZmZv8AAAAAAAAAAAAAAABmgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/wAAAAAAAAAAAAAAAGaCPv+Gq1L/hqtS/4ar
Uv+Gq1L/bIlB/2eEP/9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS
/4arUv+Gq1L/hqtS/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/AAAAAAAAAAAAAAAA
ZoI+/4arUv+Gq1L/dpZH/2aCPv9phkD/fJ5M/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9m
gj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aC
Pv8AAAAAAAAAAAAAAABmgj7/fJ5M/2mGQP9mgj7/dpZH/4arUv+Gq1L/ZoI+/4arUv+Gq1L/2tra
/9ra2v+Gq1L/hqtS/2aCPv+Gq1L/hqtS/9ra2v/a2tr/hqtS/4arUv9mgj7/hqtS/4arUv/a2tr/
2tra/4arUv+Gq1L/ZoI+/wAAAAAAAAAAAAAAAGaCPv9nhD//bIlB/4arUv+Gq1L/hqtS/4arUv9m
gj7/hqtS/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aC
Pv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/AAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////////////////wAAAAcAAAAHAAAABwAA
AAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAA
BwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAH//////////8oAAAAGAAAADAAAAABACAA
AAAAAGAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2dn
Z/9nZ2f/Z2dn/2dnZ/9nZ2f/Z2dn/2dnZ/9nZ2f/Z2dn/2dnZ/9nZ2f/Z2dn/2ZmZv9mZmb/AAAA
AAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////////////////////
/////7CwsP////////////////////////////////9nZ2f/AAAAAAAAAAAAAAAAZoI+/4arUv/a
2tr/2tra/9ra2v+Gq1L/ZoI+/////////////////////////////////5mZmf//////////////
//////////////////9nZ2f/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+
/////////////////////////////////5mZmf////////////////////////////////9nZ2f/
AAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/5mZmf+ZmZn/mZmZ/5mZmf+Z
mZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/7CwsP9nZ2f/AAAAAAAAAAAAAAAAZoI+/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/////////////////////////////////5mZmf//////////
//////////////////////9nZ2f/AAAAAAAAAAAAAAAAZoI+/4arUv/a2tr/2tra/9ra2v+Gq1L/
ZoI+/////////////////////////////////5mZmf////////////////////////////////9n
Z2f/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////////////
/////////////5mZmf////////////////////////////////9nZ2f/AAAAAAAAAAAAAAAAZoI+
/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/7CwsP9nZ2f/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+G
q1L/ZoI+/////////////////////////////////5mZmf//////////////////////////////
//9nZ2f/AAAAAAAAAAAAAAAAZoI+/4arUv/a2tr/2tra/9ra2v+Gq1L/ZoI+////////////////
/////////////////5mZmf////////////////////////////////9nZ2f/AAAAAAAAAAAAAAAA
ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/////////////////////////////////5mZmf//
//////////////////////////////9nZ2f/AAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aC
Pv9mgj7/ZoI+/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ
/7CwsP9nZ2f/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////
/////////////////////5mZmf////////////////////////////////9nZ2f/AAAAAAAAAAAA
AAAAZoI+/4arUv/a2tr/2tra/9ra2v+Gq1L/ZoI+/////////////////////////////////5mZ
mf////////////////////////////////9nZ2f/AAAAAAAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS
/4arUv+Gq1L/ZoI+/////////////////////////////////7CwsP//////////////////////
//////////9nZ2f/AAAAAAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/AAAAAAAA
AAAAAAAAZoI+/4arUv+Gq1L/gqZQ/2qIQf9ngz//ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/hqtS
/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/AAAAAAAAAAAAAAAAZoI+/4KmUP9qiEH/
ZoI+/2qGQP9/ok7/ZoI+/4arUv+Gq1L/2tra/9ra2v+Gq1L/hqtS/2aCPv+Gq1L/hqtS/9ra2v/a
2tr/hqtS/4arUv9mgj7/AAAAAAAAAAAAAAAAZoI+/2aDPv9qhkD/f6JO/4arUv+Gq1L/ZoI+/4ar
Uv+Gq1L/hqtS/4arUv+Gq1L/hqtS/2aCPv+Gq1L/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/AAAA
AAAAAAAAAAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/AAAAAAAAAAAAAAAA////AP///wD/
//8AAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAA
BwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAKAAAABQAAAAoAAAAAQAgAAAAAACQBgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2lpaf9paWn/
aWlp/2lpaf9paWn/aWlp/2lpaf9paWn/aWlp/2lpaf9paWn/ZmZm/wAAAAAAAAAAZoI+/4arUv+G
q1L/hqtS/4arUv9mgj7///////////////////////////+wsLD/////////////////////////
//9paWn/AAAAAAAAAABmgj7/hqtS/9ra2v/a2tr/hqtS/2aCPv//////////////////////////
/5mZmf///////////////////////////2lpaf8AAAAAAAAAAGaCPv+Gq1L/hqtS/4arUv+Gq1L/
ZoI+////////////////////////////mZmZ////////////////////////////aWlp/wAAAAAA
AAAAZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZ
mf+ZmZn/mZmZ/7CwsP9paWn/AAAAAAAAAABmgj7/hqtS/4arUv+Gq1L/hqtS/2aCPv//////////
/////////////////5mZmf///////////////////////////2lpaf8AAAAAAAAAAGaCPv+Gq1L/
2tra/9ra2v+Gq1L/ZoI+////////////////////////////mZmZ////////////////////////
////aWlp/wAAAAAAAAAAZoI+/4arUv+Gq1L/hqtS/4arUv9mgj7/////////////////////////
//+ZmZn///////////////////////////9paWn/AAAAAAAAAABmgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/sLCw/2lpaf8AAAAA
AAAAAGaCPv+Gq1L/hqtS/4arUv+Gq1L/ZoI+////////////////////////////mZmZ////////
////////////////////aWlp/wAAAAAAAAAAZoI+/4arUv/a2tr/2tra/4arUv9mgj7/////////
//////////////////+ZmZn///////////////////////////9paWn/AAAAAAAAAABmgj7/hqtS
/4arUv+Gq1L/hqtS/2aCPv///////////////////////////7CwsP//////////////////////
/////2lpaf8AAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/wAAAAAAAAAAZoI+/4arUv+Gq1L/b45E/2eE
P/9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/hqtS/4arUv+Gq1L/hqtS/4arUv9mgj7/AAAA
AAAAAABmgj7/fJ5M/2eEP/9nhD//fJ5M/2aCPv+Gq1L/hqtS/9ra2v+Gq1L/hqtS/2aCPv+Gq1L/
hqtS/9ra2v+Gq1L/hqtS/2aCPv8AAAAAAAAAAGaCPv9nhD//b45E/4arUv+Gq1L/ZoI+/4arUv+G
q1L/hqtS/4arUv+Gq1L/ZoI+/4arUv+Gq1L/hqtS/4arUv+Gq1L/ZoI+/wAAAAAAAAAAZoI+/2aC
Pv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/AAAAAAAAAAD///AA///wAP//8AAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAA
AAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwACgAAAAQAAAAIAAAAAEAIAAA
AAAAQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGaCPv9mgj7/ZoI+/2aCPv9mgj7/
aWlp/2lpaf9paWn/aWlp/2lpaf9paWn/aWlp/2lpaf9paWn/ZmZm/wAAAABmgj7/hqtS/4arUv+G
q1L/ZoI+//////////////////////+wsLD//////////////////////2lpaf8AAAAAZoI+/4ar
Uv/a2tr/hqtS/2aCPv//////////////////////mZmZ//////////////////////9paWn/AAAA
AGaCPv9mgj7/ZoI+/2aCPv9mgj7/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+wsLD/
aWlp/wAAAABmgj7/hqtS/4arUv+Gq1L/ZoI+//////////////////////+ZmZn/////////////
/////////2lpaf8AAAAAZoI+/4arUv/a2tr/hqtS/2aCPv//////////////////////mZmZ////
//////////////////9paWn/AAAAAGaCPv+Gq1L/hqtS/4arUv9mgj7/////////////////////
/5mZmf//////////////////////aWlp/wAAAABmgj7/ZoI+/2aCPv9mgj7/ZoI+/5mZmf+ZmZn/
mZmZ/5mZmf+ZmZn/mZmZ/5mZmf+ZmZn/sLCw/2lpaf8AAAAAZoI+/4arUv+Gq1L/hqtS/2aCPv//
////////////////////mZmZ//////////////////////9paWn/AAAAAGaCPv+Gq1L/2tra/4ar
Uv9mgj7//////////////////////5mZmf//////////////////////aWlp/wAAAABmgj7/hqtS
/4arUv+Gq1L/ZoI+//////////////////////+wsLD//////////////////////2lpaf8AAAAA
ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9m
gj7/AAAAAGaCPv+Gq1L/hqtS/4arUv9mgj7/hqtS/4arUv+Gq1L/hqtS/2aCPv+Gq1L/hqtS/4ar
Uv+Gq1L/ZoI+/wAAAABmgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+/2aCPv9mgj7/ZoI+
/2aCPv9mgj7/ZoI+/2aCPv8AAAAA//8AAP//AAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAA
AAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAA==')
	#endregion
	$formEnergiaRaport.Margin = '5, 6, 5, 6'
	$formEnergiaRaport.Name = 'formEnergiaRaport'
	$formEnergiaRaport.Text = 'Energia - raport'
	$formEnergiaRaport.add_Load($formEnergiaRaport_Load)
	#
	# textbox1
	#
	$textbox1.Location = '25, 242'
	$textbox1.Margin = '5, 6, 5, 6'
	$textbox1.Multiline = $True
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '699, 134'
	$textbox1.TabIndex = 7
	#
	# buttonGenerujRaport
	#
	$buttonGenerujRaport.Font = 'Microsoft Sans Serif, 8pt'
	$buttonGenerujRaport.Location = '494, 161'
	$buttonGenerujRaport.Margin = '5, 6, 5, 6'
	$buttonGenerujRaport.Name = 'buttonGenerujRaport'
	$buttonGenerujRaport.Size = '230, 41'
	$buttonGenerujRaport.TabIndex = 6
	$buttonGenerujRaport.Text = 'Generuj raport'
	$buttonGenerujRaport.UseCompatibleTextRendering = $True
	$buttonGenerujRaport.UseVisualStyleBackColor = $True
	$buttonGenerujRaport.add_Click($buttonGenerujRaport_Click)
	#
	# labelProszęKatalogDocelow
	#
	$labelProszęKatalogDocelow.Enabled = $False
	$labelProszęKatalogDocelow.Location = '179, 100'
	$labelProszęKatalogDocelow.Margin = '5, 0, 5, 0'
	$labelProszęKatalogDocelow.Name = 'labelProszęKatalogDocelow'
	$labelProszęKatalogDocelow.Size = '253, 30'
	$labelProszęKatalogDocelow.TabIndex = 5
	$labelProszęKatalogDocelow.Text = 'proszę katalog docelowy'
	$labelProszęKatalogDocelow.UseCompatibleTextRendering = $True
	$labelProszęKatalogDocelow.add_Click($labelProszęKatalogDocelow_Click)
	#
	# labelKatalogDocelowy
	#
	$labelKatalogDocelowy.AutoSize = $True
	$labelKatalogDocelowy.Location = '25, 100'
	$labelKatalogDocelowy.Margin = '5, 0, 5, 0'
	$labelKatalogDocelowy.Name = 'labelKatalogDocelowy'
	$labelKatalogDocelowy.Size = '156, 30'
	$labelKatalogDocelowy.TabIndex = 4
	$labelKatalogDocelowy.Text = 'Katalog docelowy:'
	$labelKatalogDocelowy.UseCompatibleTextRendering = $True
	$labelKatalogDocelowy.add_Click($labelKatalogDocelowy_Click)
	#
	# buttonWybierzKatalogDocelo
	#
	$buttonWybierzKatalogDocelo.Font = 'Microsoft Sans Serif, 8pt'
	$buttonWybierzKatalogDocelo.Location = '494, 92'
	$buttonWybierzKatalogDocelo.Margin = '5, 6, 5, 6'
	$buttonWybierzKatalogDocelo.Name = 'buttonWybierzKatalogDocelo'
	$buttonWybierzKatalogDocelo.Size = '230, 41'
	$buttonWybierzKatalogDocelo.TabIndex = 3
	$buttonWybierzKatalogDocelo.Text = 'Wybierz katalog docelowy'
	$buttonWybierzKatalogDocelo.UseCompatibleTextRendering = $True
	$buttonWybierzKatalogDocelo.UseVisualStyleBackColor = $True
	$buttonWybierzKatalogDocelo.add_Click($buttonWybierzKatalogDocelo_Click)
	#
	# labelProszęWybraćPlikŹród
	#
	$labelProszęWybraćPlikŹród.Enabled = $False
	$labelProszęWybraćPlikŹród.Location = '179, 40'
	$labelProszęWybraćPlikŹród.Margin = '5, 0, 5, 0'
	$labelProszęWybraćPlikŹród.MinimumSize = '0, 30'
	$labelProszęWybraćPlikŹród.Name = 'labelProszęWybraćPlikŹród'
	$labelProszęWybraćPlikŹród.Size = '253, 30'
	$labelProszęWybraćPlikŹród.TabIndex = 2
	$labelProszęWybraćPlikŹród.Text = 'proszę wybrać plik źródłowy'
	$labelProszęWybraćPlikŹród.UseCompatibleTextRendering = $True
	$labelProszęWybraćPlikŹród.add_Click($labelProszęWybraćPlikŹród_Click)
	#
	# buttonWybierzPlikRaportu
	#
	$buttonWybierzPlikRaportu.Font = 'Microsoft Sans Serif, 8pt'
	$buttonWybierzPlikRaportu.Location = '494, 40'
	$buttonWybierzPlikRaportu.Margin = '5, 6, 5, 6'
	$buttonWybierzPlikRaportu.Name = 'buttonWybierzPlikRaportu'
	$buttonWybierzPlikRaportu.Size = '230, 40'
	$buttonWybierzPlikRaportu.TabIndex = 1
	$buttonWybierzPlikRaportu.Text = 'Wybierz plik raportu'
	$buttonWybierzPlikRaportu.UseCompatibleTextRendering = $True
	$buttonWybierzPlikRaportu.UseVisualStyleBackColor = $True
	$buttonWybierzPlikRaportu.add_Click($buttonWybierzPlikRaportu_Click)
	#
	# labelPlikRaportuSAP
	#
	$labelPlikRaportuSAP.AutoSize = $True
	$labelPlikRaportuSAP.Location = '25, 40'
	$labelPlikRaportuSAP.Margin = '5, 0, 5, 0'
	$labelPlikRaportuSAP.Name = 'labelPlikRaportuSAP'
	$labelPlikRaportuSAP.Size = '154, 30'
	$labelPlikRaportuSAP.TabIndex = 0
	$labelPlikRaportuSAP.Text = 'Plik raportu (SAP):'
	$labelPlikRaportuSAP.UseCompatibleTextRendering = $True
	$labelPlikRaportuSAP.add_Click($labelPlikRaportuSAP_Click)
	#
	# openfiledialog1
	#
	$openfiledialog1.Filter = '|*.xlsx'
	$openfiledialog1.InitialDirectory = "$env:USERPROFILE\Desktop"
	$openfiledialog1.Title = 'plik raportu (SAP)'
	$openfiledialog1.add_FileOk($openfiledialog1_FileOk)
	#
	# folderbrowsermoderndialog1
	#
	$folderbrowsermoderndialog1.InitialDirectory = "$env:USERPROFILE\Desktop"
	$folderbrowsermoderndialog1.SelectedPath = "$env:USERPROFILE\Desktop"
	$formEnergiaRaport.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formEnergiaRaport.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formEnergiaRaport.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formEnergiaRaport.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formEnergiaRaport.ShowDialog()

} #End Function

#Call the form
Show-GUI_psf | Out-Null
