#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 43405cf1-a9cb-4745-adff-b2a7c40d2e2f
# Source File: C:\Users\plkarmic\PRV\Sync\GoLang\EnergyXLSX\GUI.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2018 v5.5.152
     Generated on:       2018-10-10 15:54
     Generated by:       plkarmicadmin
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2018
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-GUI_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Define SAPIEN Types
	#----------------------------------------------
	try{
		[FolderBrowserModernDialog] | Out-Null
	}
	catch
	{
		Add-Type -ReferencedAssemblies ('System.Windows.Forms') -TypeDefinition  @" 
		using System;
		using System.Windows.Forms;
		using System.Reflection;

        namespace SAPIENTypes
        {
		    public class FolderBrowserModernDialog : System.Windows.Forms.CommonDialog
            {
                private System.Windows.Forms.OpenFileDialog fileDialog;
                public FolderBrowserModernDialog()
                {
                    fileDialog = new System.Windows.Forms.OpenFileDialog();
                    fileDialog.Filter = "Folders|\n";
                    fileDialog.AddExtension = false;
                    fileDialog.CheckFileExists = false;
                    fileDialog.DereferenceLinks = true;
                    fileDialog.Multiselect = false;
                    fileDialog.Title = "Select a folder";
                }

                public string Title
                {
                    get { return fileDialog.Title; }
                    set { fileDialog.Title = value; }
                }

                public string InitialDirectory
                {
                    get { return fileDialog.InitialDirectory; }
                    set { fileDialog.InitialDirectory = value; }
                }
                
                public string SelectedPath
                {
                    get { return fileDialog.FileName; }
                    set { fileDialog.FileName = value; }
                }

                object InvokeMethod(Type type, object obj, string method, object[] parameters)
                {
                    MethodInfo methInfo = type.GetMethod(method, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                    return methInfo.Invoke(obj, parameters);
                }

                bool ShowOriginalBrowserDialog(IntPtr hwndOwner)
                {
                    using(FolderBrowserDialog folderBrowserDialog = new FolderBrowserDialog())
                    {
                        folderBrowserDialog.Description = this.Title;
                        folderBrowserDialog.SelectedPath = !string.IsNullOrEmpty(this.SelectedPath) ? this.SelectedPath : this.InitialDirectory;
                        folderBrowserDialog.ShowNewFolderButton = false;
                        if (folderBrowserDialog.ShowDialog() == DialogResult.OK)
                        {
                            fileDialog.FileName = folderBrowserDialog.SelectedPath;
                            return true;
                        }
                        return false;
                    }
                }

                protected override bool RunDialog(IntPtr hwndOwner)
                {
                    if (Environment.OSVersion.Version.Major >= 6)
                    {      
                        try
                        {
                            bool flag = false;
                            System.Reflection.Assembly assembly = Assembly.Load("System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
                            Type typeIFileDialog = assembly.GetType("System.Windows.Forms.FileDialogNative").GetNestedType("IFileDialog", BindingFlags.NonPublic);
                            uint num = 0;
                            object dialog = InvokeMethod(fileDialog.GetType(), fileDialog, "CreateVistaDialog", null);
                            InvokeMethod(fileDialog.GetType(), fileDialog, "OnBeforeVistaDialog", new object[] { dialog });
                            uint options = (uint)InvokeMethod(typeof(System.Windows.Forms.FileDialog), fileDialog, "GetOptions", null) | (uint)0x20;
                            InvokeMethod(typeIFileDialog, dialog, "SetOptions", new object[] { options });
                            Type vistaDialogEventsType = assembly.GetType("System.Windows.Forms.FileDialog").GetNestedType("VistaDialogEvents", BindingFlags.NonPublic);
                            object pfde = Activator.CreateInstance(vistaDialogEventsType, fileDialog);
                            object[] parameters = new object[] { pfde, num };
                            InvokeMethod(typeIFileDialog, dialog, "Advise", parameters);
                            num = (uint)parameters[1];
                            try
                            {
                                int num2 = (int)InvokeMethod(typeIFileDialog, dialog, "Show", new object[] { hwndOwner });
                                flag = 0 == num2;
                            }
                            finally
                            {
                                InvokeMethod(typeIFileDialog, dialog, "Unadvise", new object[] { num });
                                GC.KeepAlive(pfde);
                            }
                            return flag;
                        }
                        catch
                        {
                            return ShowOriginalBrowserDialog(hwndOwner);
                        }
                    }
                    else
                        return ShowOriginalBrowserDialog(hwndOwner);
                }

                public override void Reset()
                {
                    fileDialog.Reset();
                }
            }
       }
"@ -IgnoreWarnings | Out-Null
	}
	#endregion Define SAPIEN Types

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$buttonGenerujRaport = New-Object 'System.Windows.Forms.Button'
	$labelProszęKatalogDocelow = New-Object 'System.Windows.Forms.Label'
	$labelKatalogDocelowy = New-Object 'System.Windows.Forms.Label'
	$buttonWybierzKatalogDocelo = New-Object 'System.Windows.Forms.Button'
	$labelProszęWybraćPlikŹród = New-Object 'System.Windows.Forms.Label'
	$buttonWybierzPlikRaportu = New-Object 'System.Windows.Forms.Button'
	$labelPlikRaportuSAP = New-Object 'System.Windows.Forms.Label'
	$openfiledialog1 = New-Object 'System.Windows.Forms.OpenFileDialog'
	$folderbrowsermoderndialog1 = New-Object 'SAPIENTypes.FolderBrowserModernDialog'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	$labelPlikRaportuSAP_Click={
		#TODO: Place custom script here
		
	}
	
	$openfiledialog1_FileOk=[System.ComponentModel.CancelEventHandler]{
	#Event Argument: $_ = [System.ComponentModel.CancelEventArgs]
		#TODO: Place custom script here
		
	}
	
	$buttonWybierzPlikRaportu_Click={
		#TODO: Place custom script here
		$openfiledialog1.ShowDialog()
		$global:fileName = $openfiledialog1.FileName
		$labelProszęWybraćPlikŹród.Text = $global:fileName
		$textbox1.Text += "Plik raportu SAP: $global:fileName `r`n"
	}
	
	$labelKatalogDocelowy_Click={
		#TODO: Place custom script here
		
	}
	
	$labelProszęWybraćPlikŹród_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonWybierzKatalogDocelo_Click={
		#TODO: Place custom script here
		$folderbrowsermoderndialog1.ShowDialog()
		$global:folderDocelowy = $folderbrowsermoderndialog1.SelectedPath
		$labelProszęKatalogDocelow.Text = $global:folderDocelowy
		$textbox1.Text += "Folder docelowy: $global:folderDocelow `r`n"
	}
	
	$labelProszęKatalogDocelow_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonGenerujRaport_Click={
		#TODO: Place custom script here
		Write-Host $global:fileName
		Write-Host $global:folderDocelowy
		Write-Host "Uruchamiam process: raportEnergia.exe " $global:fileName $global:folderDocelowy
		#Start-Process raportEnergia.exe -ArgumentList "$global:fileName $global:folderDocelowy" -Wait
		$cmdOutput = & .\raportEnergia.exe $global:fileName $global:folderDocelowy
		$textbox1.Text += "GOTOWE `n`n"
		$textbox1.Text += "$cmdOutput `n`n"
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonGenerujRaport.remove_Click($buttonGenerujRaport_Click)
			$labelProszęKatalogDocelow.remove_Click($labelProszęKatalogDocelow_Click)
			$labelKatalogDocelowy.remove_Click($labelKatalogDocelowy_Click)
			$buttonWybierzKatalogDocelo.remove_Click($buttonWybierzKatalogDocelo_Click)
			$labelProszęWybraćPlikŹród.remove_Click($labelProszęWybraćPlikŹród_Click)
			$buttonWybierzPlikRaportu.remove_Click($buttonWybierzPlikRaportu_Click)
			$labelPlikRaportuSAP.remove_Click($labelPlikRaportuSAP_Click)
			$form1.remove_Load($form1_Load)
			$openfiledialog1.remove_FileOk($openfiledialog1_FileOk)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($textbox1)
	$form1.Controls.Add($buttonGenerujRaport)
	$form1.Controls.Add($labelProszęKatalogDocelow)
	$form1.Controls.Add($labelKatalogDocelowy)
	$form1.Controls.Add($buttonWybierzKatalogDocelo)
	$form1.Controls.Add($labelProszęWybraćPlikŹród)
	$form1.Controls.Add($buttonWybierzPlikRaportu)
	$form1.Controls.Add($labelPlikRaportuSAP)
	$form1.AutoScaleDimensions = '10, 20'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '760, 325'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# textbox1
	#
	$textbox1.Location = '25, 194'
	$textbox1.Margin = '5, 5, 5, 5'
	$textbox1.Multiline = $True
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '699, 108'
	$textbox1.TabIndex = 7
	#
	# buttonGenerujRaport
	#
	$buttonGenerujRaport.Font = 'Microsoft Sans Serif, 8pt'
	$buttonGenerujRaport.Location = '494, 129'
	$buttonGenerujRaport.Margin = '5, 5, 5, 5'
	$buttonGenerujRaport.Name = 'buttonGenerujRaport'
	$buttonGenerujRaport.Size = '230, 33'
	$buttonGenerujRaport.TabIndex = 6
	$buttonGenerujRaport.Text = 'Generuj raport'
	$buttonGenerujRaport.UseCompatibleTextRendering = $True
	$buttonGenerujRaport.UseVisualStyleBackColor = $True
	$buttonGenerujRaport.add_Click($buttonGenerujRaport_Click)
	#
	# labelProszęKatalogDocelow
	#
	$labelProszęKatalogDocelow.Enabled = $False
	$labelProszęKatalogDocelow.Location = '179, 80'
	$labelProszęKatalogDocelow.Margin = '5, 0, 5, 0'
	$labelProszęKatalogDocelow.Name = 'labelProszęKatalogDocelow'
	$labelProszęKatalogDocelow.Size = '253, 24'
	$labelProszęKatalogDocelow.TabIndex = 5
	$labelProszęKatalogDocelow.Text = 'proszę katalog docelowy'
	$labelProszęKatalogDocelow.UseCompatibleTextRendering = $True
	$labelProszęKatalogDocelow.add_Click($labelProszęKatalogDocelow_Click)
	#
	# labelKatalogDocelowy
	#
	$labelKatalogDocelowy.AutoSize = $True
	$labelKatalogDocelowy.Location = '25, 80'
	$labelKatalogDocelowy.Margin = '5, 0, 5, 0'
	$labelKatalogDocelowy.Name = 'labelKatalogDocelowy'
	$labelKatalogDocelowy.Size = '144, 24'
	$labelKatalogDocelowy.TabIndex = 4
	$labelKatalogDocelowy.Text = 'Katalog docelowy:'
	$labelKatalogDocelowy.UseCompatibleTextRendering = $True
	$labelKatalogDocelowy.add_Click($labelKatalogDocelowy_Click)
	#
	# buttonWybierzKatalogDocelo
	#
	$buttonWybierzKatalogDocelo.Font = 'Microsoft Sans Serif, 8pt'
	$buttonWybierzKatalogDocelo.Location = '494, 74'
	$buttonWybierzKatalogDocelo.Margin = '5, 5, 5, 5'
	$buttonWybierzKatalogDocelo.Name = 'buttonWybierzKatalogDocelo'
	$buttonWybierzKatalogDocelo.Size = '230, 33'
	$buttonWybierzKatalogDocelo.TabIndex = 3
	$buttonWybierzKatalogDocelo.Text = 'Wybierz katalog docelowy'
	$buttonWybierzKatalogDocelo.UseCompatibleTextRendering = $True
	$buttonWybierzKatalogDocelo.UseVisualStyleBackColor = $True
	$buttonWybierzKatalogDocelo.add_Click($buttonWybierzKatalogDocelo_Click)
	#
	# labelProszęWybraćPlikŹród
	#
	$labelProszęWybraćPlikŹród.Enabled = $False
	$labelProszęWybraćPlikŹród.Location = '179, 32'
	$labelProszęWybraćPlikŹród.Margin = '5, 0, 5, 0'
	$labelProszęWybraćPlikŹród.MinimumSize = '0, 24'
	$labelProszęWybraćPlikŹród.Name = 'labelProszęWybraćPlikŹród'
	$labelProszęWybraćPlikŹród.Size = '253, 24'
	$labelProszęWybraćPlikŹród.TabIndex = 2
	$labelProszęWybraćPlikŹród.Text = 'proszę wybrać plik źródłowy'
	$labelProszęWybraćPlikŹród.UseCompatibleTextRendering = $True
	$labelProszęWybraćPlikŹród.add_Click($labelProszęWybraćPlikŹród_Click)
	#
	# buttonWybierzPlikRaportu
	#
	$buttonWybierzPlikRaportu.Font = 'Microsoft Sans Serif, 8pt'
	$buttonWybierzPlikRaportu.Location = '494, 32'
	$buttonWybierzPlikRaportu.Margin = '5, 5, 5, 5'
	$buttonWybierzPlikRaportu.Name = 'buttonWybierzPlikRaportu'
	$buttonWybierzPlikRaportu.Size = '230, 32'
	$buttonWybierzPlikRaportu.TabIndex = 1
	$buttonWybierzPlikRaportu.Text = 'Wybierz plik raportu'
	$buttonWybierzPlikRaportu.UseCompatibleTextRendering = $True
	$buttonWybierzPlikRaportu.UseVisualStyleBackColor = $True
	$buttonWybierzPlikRaportu.add_Click($buttonWybierzPlikRaportu_Click)
	#
	# labelPlikRaportuSAP
	#
	$labelPlikRaportuSAP.AutoSize = $True
	$labelPlikRaportuSAP.Location = '25, 32'
	$labelPlikRaportuSAP.Margin = '5, 0, 5, 0'
	$labelPlikRaportuSAP.Name = 'labelPlikRaportuSAP'
	$labelPlikRaportuSAP.Size = '146, 24'
	$labelPlikRaportuSAP.TabIndex = 0
	$labelPlikRaportuSAP.Text = 'Plik raportu (SAP):'
	$labelPlikRaportuSAP.UseCompatibleTextRendering = $True
	$labelPlikRaportuSAP.add_Click($labelPlikRaportuSAP_Click)
	#
	# openfiledialog1
	#
	$openfiledialog1.FileName = 'openfiledialog1'
	$openfiledialog1.add_FileOk($openfiledialog1_FileOk)
	#
	# folderbrowsermoderndialog1
	#
	$folderbrowsermoderndialog1.InitialDirectory = "$env:USERPROFILE\Desktop"
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-GUI_psf | Out-Null
